---
########
## CI ##
########
name: Continuous Integration

# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

####################################
# Start the job on push            #
# Don't run on push to master/main #
####################################
on:
  push:
    branches-ignore:
      - 'master'
      - 'main'

##################
# Define the Job #
##################
jobs:
  build:
    # Name the Job
    name: CI

    # Set the platform to run on
    runs-on: ubuntu-latest

    ####################
    # Define the steps #
    ####################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout
        uses: actions/checkout@v3

      #######################
      # Setup Docker BuildX #
      #######################
      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v2

      ##############################
      # Build the Docker Container #
      ##############################
      - name: Build Docker Container
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            BUILD_DATE=${{ env.BUILD_DATE }}
            BUILD_REVISION=${{ github.sha }}
            BUILD_VERSION=${{ github.sha }}
          push: false
          tags: super-cool-image:latest
          outputs: type=docker,dest=/tmp/myimage.tar

      # Upload the artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: myimage
          path: /tmp/myimage.tar
  download-container:
    needs: CI

    # Set the platform to run on
    runs-on: ubuntu-latest

    # Define the steps
    steps:
      # Setup Docker BuildX
      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v2

      # Download the artifact
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: myimage
          path: /tmp

      # Load the Docker image
      - name: Load image
        run: |
          docker load --input /tmp/myimage.tar
          docker image ls -a
