name: Output GitHub Actions Contexts

#############################
# Start the job on push     #
# Don't run on push to main #
#############################
on:
  push:
    branches-ignore:
      - main

##################
# Define the Job #
##################
jobs:
  # Name the Job
  context-info:
    # Set the platform to run on
    runs-on: ubuntu-latest

    ####################
    # Define the Steps #
    ####################
    steps:
      - name: Output GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Output Job Context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Output Step Context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Output Runner Context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Output Strategy Context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Output Matrix Context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
