name: Centralized Action

on:
  # Start the job on push
  push:
    # Don't run on push to main
    branches-ignore:
      - main

jobs:
  centralized-job:
    # Set the platform to run on
    runs-on: ubuntu-latest

    # Define the steps
    steps:
      - name: Use the Centralized Action
        uses: ncalteen-learning/centralized-workflow@main
