name: Continuous Testing

on:
  # Start the job on push
  push:
    # Don't run on push to main
    branches-ignore:
      - 'main'

jobs:
  build:
    # Name the job
    name: CT

    # Set the platform to run on
    runs-on: ubuntu-latest

    # Define the steps
    steps:
      # Checkout the codebase
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      # Run Super Linter
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
