name: Download Container from CI Workflow

on:
  # Start the job on completion of the CI workflow
  workflow_run:
    workflows:
      - CI
    types:
      - completed

jobs:
  download-container:
    # Set the platform to run on
    runs-on: ubuntu-latest

    # Define the steps
    steps:
      # Setup Docker BuildX
      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v2

      # Download the artifact
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: myimage
          path: /tmp

      # Load the Docker image
      - name: Load image
        run: |
          docker load --input /tmp/myimage.tar
          docker image ls -a
