name: Matrix Build

on:
  # Start the workflow on push
  push:
    # Don't run on push to main
    branches-ignore:
      - main

jobs:
  parallel-test:
    # Define the strategy
    # This will cause the job to run for each combination of `test` and `os`
    # E.g. (test1, macos-latest), (test2, macos-latest), ...
    strategy:
      matrix:
        test: ['test1', 'test2', 'test3']
        os: [macos-latest, ubuntu-latest, windows-latest]

    # Set the platform to run on
    # Populated from the matrix values
    runs-on: ${{ matrix.os }}

    # Define the steps
    steps:
      - name: Test ${{ matrix.test }} on ${{ matrix.os }}
        run: |
          echo "Running test: ${{ matrix.test }}"
          date
          echo "Taking a quick nap..."
          sleep 5
          date
